name: qnaplus

services:
  bot:
    image: battlesquid0101/qnaplus-bot:${QNAPLUS_TAG:-latest}
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      INFISICAL_MACHINE_CLIENT_ID: ${INFISICAL_MACHINE_CLIENT_ID}
      INFISICAL_MACHINE_CLIENT_SECRET: ${INFISICAL_MACHINE_CLIENT_SECRET}
      INFISICAL_SECRET_ENV: ${INFISICAL_SECRET_ENV:-prod}
    labels:
      dockhand.order: "1"

  updater:
    image: battlesquid0101/qnaplus-updater:${QNAPLUS_TAG:-latest}
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      INFISICAL_MACHINE_CLIENT_ID: ${INFISICAL_MACHINE_CLIENT_ID}
      INFISICAL_MACHINE_CLIENT_SECRET: ${INFISICAL_MACHINE_CLIENT_SECRET}
      INFISICAL_SECRET_ENV: ${INFISICAL_SECRET_ENV:-prod}
    labels:
      dockhand.order: "2"
