name: Bot Image

permissions:
  actions: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
    tags:
      - 'v*'
    paths:
      - .github/workflows/bot_image.yml
      - '!services/updater/**'
      - services/bot/**
      - packages/**
      - .env.vault
      - package.json
      - turbo.json
      - yarn.lock
      - .gitignore
      - docker-compose.yml
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - master

jobs:
  should_skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          do_not_skip: '["pull_request"]'
          cancel_others: true
          concurrent_skipping: always
          skip_after_successful_duplicate: false

  docker:
    needs: should_skip
    if: needs.should_skip.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      -
        name: Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            battlesquid0101/qnaplus-bot
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: services/bot/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}