name: Create Tags

on:
  push:
    branches:
      - master

jobs:
  tags:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - 
      name: Get package.json version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@v1.3.1
    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/v${{ steps.package-version.outputs.current-version}}',
            sha: context.sha
          })