name: Updater Image

on:
  push:
    branches:
      - master
      - dev
    paths:
      - .github/workflows/updater_image.yml
      - services/updater/**
      - packages/**
      - .env.vault
      - .dockerignore
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: services/updater/Dockerfile
          tags: battlesquid0101/qnaplus_updater_${{ (github.head_ref || github.ref_name) == 'master' && 'prod' || 'dev'}}:latest